#!/bin/bash
# An application process graceful killer
# Author: Alexia Michelle <alexia@goldendoglinux.org>

# It's a "semantic" process ID killer in the sense that it allows a process to be killed by its partial name
# Usage: bash sk <application name>
# example: bash sk steam

for i in $(pgrep -f -i $1);do kill $i;done
